// SPDX-License-Identifier: Apache-2.0

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"time"
)

const getAuditChainHead = `-- name: GetAuditChainHead :one
SELECT seq, hash FROM audit_events
WHERE chain_key = $1
ORDER BY seq DESC
LIMIT 1
`

type GetAuditChainHeadRow struct {
	Seq  int64
	Hash []byte
}

func (q *Queries) GetAuditChainHead(ctx context.Context, chainKey string) (GetAuditChainHeadRow, error) {
	row := q.db.QueryRow(ctx, getAuditChainHead, chainKey)
	var i GetAuditChainHeadRow
	err := row.Scan(&i.Seq, &i.Hash)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (id, chain_key, seq, org_id, occurred_at, actor_kind, actor_id, action,
    target_type, target_id, result, request_id, source_ip, user_agent, details, prev_hash, hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
`

type InsertAuditEventParams struct {
	ID         string
	ChainKey   string
	Seq        int64
	OrgID      *string
	OccurredAt time.Time
	ActorKind  string
	ActorID    string
	Action     string
	TargetType string
	TargetID   string
	Result     string
	RequestID  string
	SourceIp   string
	UserAgent  string
	Details    []byte
	PrevHash   []byte
	Hash       []byte
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ID,
		arg.ChainKey,
		arg.Seq,
		arg.OrgID,
		arg.OccurredAt,
		arg.ActorKind,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Result,
		arg.RequestID,
		arg.SourceIp,
		arg.UserAgent,
		arg.Details,
		arg.PrevHash,
		arg.Hash,
	)
	return err
}

const listAuditChain = `-- name: ListAuditChain :many
SELECT id, chain_key, seq, org_id, occurred_at, actor_kind, actor_id, action, target_type, target_id,
    result, request_id, source_ip, user_agent, details, prev_hash, hash
FROM audit_events
WHERE chain_key = $1
ORDER BY seq
`

func (q *Queries) ListAuditChain(ctx context.Context, chainKey string) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditChain, chainKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ChainKey,
			&i.Seq,
			&i.OrgID,
			&i.OccurredAt,
			&i.ActorKind,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Result,
			&i.RequestID,
			&i.SourceIp,
			&i.UserAgent,
			&i.Details,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, chain_key, seq, org_id, occurred_at, actor_kind, actor_id, action, target_type, target_id,
    result, request_id, source_ip, user_agent, details, prev_hash, hash
FROM audit_events
WHERE org_id = $1
  AND ($2::text = '' OR id < $2::text)
ORDER BY id DESC
LIMIT $3
`

type ListAuditEventsParams struct {
	OrgID    *string
	BeforeID string
	MaxRows  int32
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, arg.OrgID, arg.BeforeID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ChainKey,
			&i.Seq,
			&i.OrgID,
			&i.OccurredAt,
			&i.ActorKind,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Result,
			&i.RequestID,
			&i.SourceIp,
			&i.UserAgent,
			&i.Details,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAuditChain = `-- name: LockAuditChain :exec

SELECT pg_advisory_xact_lock(hashtextextended('kiln.audit:' || $1::text, 0))
`

// SPDX-License-Identifier: Apache-2.0
// LockAuditChain serializes appends to one chain for the current transaction.
func (q *Queries) LockAuditChain(ctx context.Context, chainKey string) error {
	_, err := q.db.Exec(ctx, lockAuditChain, chainKey)
	return err
}
