// SPDX-License-Identifier: Apache-2.0

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github.sql

package db

import (
	"context"
	"time"
)

const bindGitHubInstallation = `-- name: BindGitHubInstallation :exec

INSERT INTO github_installations (installation_id, org_id, account_login, bound_by, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type BindGitHubInstallationParams struct {
	InstallationID int64
	OrgID          string
	AccountLogin   string
	BoundBy        *string
	CreatedAt      time.Time
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) BindGitHubInstallation(ctx context.Context, arg BindGitHubInstallationParams) error {
	_, err := q.db.Exec(ctx, bindGitHubInstallation,
		arg.InstallationID,
		arg.OrgID,
		arg.AccountLogin,
		arg.BoundBy,
		arg.CreatedAt,
	)
	return err
}

const claimCommitStatuses = `-- name: ClaimCommitStatuses :many
SELECT id, installation_id, repo_id, commit_sha, state, context, description, target_url, attempts
FROM commit_status_outbox
WHERE sent_at IS NULL AND next_attempt_at <= $1
ORDER BY id
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ClaimCommitStatusesParams struct {
	Now     time.Time
	MaxRows int32
}

type ClaimCommitStatusesRow struct {
	ID             string
	InstallationID int64
	RepoID         int64
	CommitSha      string
	State          string
	Context        string
	Description    string
	TargetUrl      string
	Attempts       int32
}

func (q *Queries) ClaimCommitStatuses(ctx context.Context, arg ClaimCommitStatusesParams) ([]ClaimCommitStatusesRow, error) {
	rows, err := q.db.Query(ctx, claimCommitStatuses, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimCommitStatusesRow{}
	for rows.Next() {
		var i ClaimCommitStatusesRow
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.RepoID,
			&i.CommitSha,
			&i.State,
			&i.Context,
			&i.Description,
			&i.TargetUrl,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimWebhookDeliveries = `-- name: ClaimWebhookDeliveries :many
SELECT id, event, payload, attempts
FROM webhook_deliveries
WHERE status = 'pending' AND next_attempt_at <= $1
ORDER BY received_at
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ClaimWebhookDeliveriesParams struct {
	Now     time.Time
	MaxRows int32
}

type ClaimWebhookDeliveriesRow struct {
	ID       string
	Event    string
	Payload  []byte
	Attempts int32
}

func (q *Queries) ClaimWebhookDeliveries(ctx context.Context, arg ClaimWebhookDeliveriesParams) ([]ClaimWebhookDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, claimWebhookDeliveries, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimWebhookDeliveriesRow{}
	for rows.Next() {
		var i ClaimWebhookDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Event,
			&i.Payload,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteGitHubInstallation = `-- name: DeleteGitHubInstallation :execrows
DELETE FROM github_installations WHERE installation_id = $1
`

func (q *Queries) DeleteGitHubInstallation(ctx context.Context, installationID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGitHubInstallation, installationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldWebhookDeliveries = `-- name: DeleteOldWebhookDeliveries :execrows
DELETE FROM webhook_deliveries WHERE received_at < $1
`

func (q *Queries) DeleteOldWebhookDeliveries(ctx context.Context, receivedAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldWebhookDeliveries, receivedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableGitHubInstallation = `-- name: DisableGitHubInstallation :exec
UPDATE github_installations SET disabled_at = COALESCE(disabled_at, $1)
WHERE installation_id = $2
`

type DisableGitHubInstallationParams struct {
	Now            *time.Time
	InstallationID int64
}

func (q *Queries) DisableGitHubInstallation(ctx context.Context, arg DisableGitHubInstallationParams) error {
	_, err := q.db.Exec(ctx, disableGitHubInstallation, arg.Now, arg.InstallationID)
	return err
}

const disableRepositoriesByRepoID = `-- name: DisableRepositoriesByRepoID :exec
UPDATE repositories SET disabled_at = COALESCE(disabled_at, $1)
WHERE installation_id = $2 AND repo_id = ANY($3::bigint[])
`

type DisableRepositoriesByRepoIDParams struct {
	Now            *time.Time
	InstallationID int64
	RepoIds        []int64
}

func (q *Queries) DisableRepositoriesByRepoID(ctx context.Context, arg DisableRepositoriesByRepoIDParams) error {
	_, err := q.db.Exec(ctx, disableRepositoriesByRepoID, arg.Now, arg.InstallationID, arg.RepoIds)
	return err
}

const disableRepositoriesForInstallation = `-- name: DisableRepositoriesForInstallation :exec
UPDATE repositories SET disabled_at = COALESCE(disabled_at, $1)
WHERE installation_id = $2
`

type DisableRepositoriesForInstallationParams struct {
	Now            *time.Time
	InstallationID int64
}

func (q *Queries) DisableRepositoriesForInstallation(ctx context.Context, arg DisableRepositoriesForInstallationParams) error {
	_, err := q.db.Exec(ctx, disableRepositoriesForInstallation, arg.Now, arg.InstallationID)
	return err
}

const finishWebhookDelivery = `-- name: FinishWebhookDelivery :exec
UPDATE webhook_deliveries
SET status = $1, outcome = $2, processed_at = $3, attempts = attempts + 1
WHERE id = $4
`

type FinishWebhookDeliveryParams struct {
	Status  string
	Outcome string
	Now     *time.Time
	ID      string
}

func (q *Queries) FinishWebhookDelivery(ctx context.Context, arg FinishWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, finishWebhookDelivery,
		arg.Status,
		arg.Outcome,
		arg.Now,
		arg.ID,
	)
	return err
}

const getActiveRepositoryByRepoID = `-- name: GetActiveRepositoryByRepoID :one
SELECT r.id, r.org_id, r.project_id, r.installation_id, r.repo_id, r.full_name, r.clone_url,
    r.default_branch, r.private, r.linked_by, r.created_at, r.disabled_at
FROM repositories r
JOIN github_installations i ON i.installation_id = r.installation_id AND i.org_id = r.org_id
WHERE r.repo_id = $1 AND r.disabled_at IS NULL AND i.disabled_at IS NULL
`

// GetActiveRepositoryByRepoID finds the enabled link for a GitHub repository
// whose installation is bound and enabled.
func (q *Queries) GetActiveRepositoryByRepoID(ctx context.Context, repoID int64) (Repository, error) {
	row := q.db.QueryRow(ctx, getActiveRepositoryByRepoID, repoID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.InstallationID,
		&i.RepoID,
		&i.FullName,
		&i.CloneUrl,
		&i.DefaultBranch,
		&i.Private,
		&i.LinkedBy,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getGitHubInstallation = `-- name: GetGitHubInstallation :one
SELECT installation_id, org_id, account_login, bound_by, created_at, disabled_at
FROM github_installations
WHERE installation_id = $1
`

func (q *Queries) GetGitHubInstallation(ctx context.Context, installationID int64) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, getGitHubInstallation, installationID)
	var i GithubInstallation
	err := row.Scan(
		&i.InstallationID,
		&i.OrgID,
		&i.AccountLogin,
		&i.BoundBy,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getRepositoryForProject = `-- name: GetRepositoryForProject :one
SELECT id, org_id, project_id, installation_id, repo_id, full_name, clone_url, default_branch, private,
    linked_by, created_at, disabled_at
FROM repositories
WHERE org_id = $1 AND project_id = $2
`

type GetRepositoryForProjectParams struct {
	OrgID     string
	ProjectID string
}

func (q *Queries) GetRepositoryForProject(ctx context.Context, arg GetRepositoryForProjectParams) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryForProject, arg.OrgID, arg.ProjectID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.InstallationID,
		&i.RepoID,
		&i.FullName,
		&i.CloneUrl,
		&i.DefaultBranch,
		&i.Private,
		&i.LinkedBy,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getRunStatusTarget = `-- name: GetRunStatusTarget :one
SELECT r.repo_id, r.installation_id, p.slug AS project_slug, o.slug AS org_slug
FROM repositories r
JOIN projects p ON p.org_id = r.org_id AND p.id = r.project_id
JOIN orgs o ON o.id = r.org_id
JOIN github_installations i ON i.installation_id = r.installation_id AND i.org_id = r.org_id
WHERE r.org_id = $1 AND r.project_id = $2 AND r.disabled_at IS NULL AND i.disabled_at IS NULL
`

type GetRunStatusTargetParams struct {
	OrgID     string
	ProjectID string
}

type GetRunStatusTargetRow struct {
	RepoID         int64
	InstallationID int64
	ProjectSlug    string
	OrgSlug        string
}

// GetRunStatusTarget returns what a commit status for a run needs.
func (q *Queries) GetRunStatusTarget(ctx context.Context, arg GetRunStatusTargetParams) (GetRunStatusTargetRow, error) {
	row := q.db.QueryRow(ctx, getRunStatusTarget, arg.OrgID, arg.ProjectID)
	var i GetRunStatusTargetRow
	err := row.Scan(
		&i.RepoID,
		&i.InstallationID,
		&i.ProjectSlug,
		&i.OrgSlug,
	)
	return i, err
}

const insertCommitStatus = `-- name: InsertCommitStatus :exec
INSERT INTO commit_status_outbox (id, org_id, run_id, repo_id, installation_id, commit_sha, state, context,
    description, target_url, created_at, next_attempt_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $11)
`

type InsertCommitStatusParams struct {
	ID             string
	OrgID          string
	RunID          string
	RepoID         int64
	InstallationID int64
	CommitSha      string
	State          string
	Context        string
	Description    string
	TargetUrl      string
	CreatedAt      time.Time
}

func (q *Queries) InsertCommitStatus(ctx context.Context, arg InsertCommitStatusParams) error {
	_, err := q.db.Exec(ctx, insertCommitStatus,
		arg.ID,
		arg.OrgID,
		arg.RunID,
		arg.RepoID,
		arg.InstallationID,
		arg.CommitSha,
		arg.State,
		arg.Context,
		arg.Description,
		arg.TargetUrl,
		arg.CreatedAt,
	)
	return err
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :execrows
INSERT INTO webhook_deliveries (id, delivery_id, body_sha256, event, payload, received_at, next_attempt_at)
VALUES ($1, $2, $3, $4, $5, $6, $6)
ON CONFLICT DO NOTHING
`

type InsertWebhookDeliveryParams struct {
	ID         string
	DeliveryID string
	BodySha256 []byte
	Event      string
	Payload    []byte
	ReceivedAt time.Time
}

func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertWebhookDelivery,
		arg.ID,
		arg.DeliveryID,
		arg.BodySha256,
		arg.Event,
		arg.Payload,
		arg.ReceivedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const linkRepository = `-- name: LinkRepository :exec
INSERT INTO repositories (id, org_id, project_id, installation_id, repo_id, full_name, clone_url,
    default_branch, private, linked_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type LinkRepositoryParams struct {
	ID             string
	OrgID          string
	ProjectID      string
	InstallationID int64
	RepoID         int64
	FullName       string
	CloneUrl       string
	DefaultBranch  string
	Private        bool
	LinkedBy       *string
	CreatedAt      time.Time
}

func (q *Queries) LinkRepository(ctx context.Context, arg LinkRepositoryParams) error {
	_, err := q.db.Exec(ctx, linkRepository,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.InstallationID,
		arg.RepoID,
		arg.FullName,
		arg.CloneUrl,
		arg.DefaultBranch,
		arg.Private,
		arg.LinkedBy,
		arg.CreatedAt,
	)
	return err
}

const listGitHubInstallationsForOrg = `-- name: ListGitHubInstallationsForOrg :many
SELECT installation_id, org_id, account_login, bound_by, created_at, disabled_at
FROM github_installations
WHERE org_id = $1
ORDER BY installation_id
`

func (q *Queries) ListGitHubInstallationsForOrg(ctx context.Context, orgID string) ([]GithubInstallation, error) {
	rows, err := q.db.Query(ctx, listGitHubInstallationsForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubInstallation{}
	for rows.Next() {
		var i GithubInstallation
		if err := rows.Scan(
			&i.InstallationID,
			&i.OrgID,
			&i.AccountLogin,
			&i.BoundBy,
			&i.CreatedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCommitStatusSent = `-- name: MarkCommitStatusSent :exec
UPDATE commit_status_outbox SET sent_at = $1, attempts = attempts + 1 WHERE id = $2
`

type MarkCommitStatusSentParams struct {
	Now *time.Time
	ID  string
}

func (q *Queries) MarkCommitStatusSent(ctx context.Context, arg MarkCommitStatusSentParams) error {
	_, err := q.db.Exec(ctx, markCommitStatusSent, arg.Now, arg.ID)
	return err
}

const retryCommitStatus = `-- name: RetryCommitStatus :exec
UPDATE commit_status_outbox SET attempts = attempts + 1, next_attempt_at = $1
WHERE id = $2
`

type RetryCommitStatusParams struct {
	NextAttemptAt time.Time
	ID            string
}

func (q *Queries) RetryCommitStatus(ctx context.Context, arg RetryCommitStatusParams) error {
	_, err := q.db.Exec(ctx, retryCommitStatus, arg.NextAttemptAt, arg.ID)
	return err
}

const retryWebhookDelivery = `-- name: RetryWebhookDelivery :exec
UPDATE webhook_deliveries
SET attempts = attempts + 1, next_attempt_at = $1, outcome = $2
WHERE id = $3
`

type RetryWebhookDeliveryParams struct {
	NextAttemptAt time.Time
	Outcome       string
	ID            string
}

func (q *Queries) RetryWebhookDelivery(ctx context.Context, arg RetryWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, retryWebhookDelivery, arg.NextAttemptAt, arg.Outcome, arg.ID)
	return err
}

const supersedeCommitStatuses = `-- name: SupersedeCommitStatuses :exec
UPDATE commit_status_outbox o SET sent_at = $1
WHERE o.sent_at IS NULL AND EXISTS (
    SELECT 1 FROM commit_status_outbox n
    WHERE n.repo_id = o.repo_id AND n.commit_sha = o.commit_sha AND n.context = o.context AND n.id > o.id)
`

// SupersedeCommitStatuses marks unsent statuses that a newer one for the same
// commit and context replaces, so an old state never overwrites a new one.
func (q *Queries) SupersedeCommitStatuses(ctx context.Context, now *time.Time) error {
	_, err := q.db.Exec(ctx, supersedeCommitStatuses, now)
	return err
}

const unlinkRepository = `-- name: UnlinkRepository :execrows
DELETE FROM repositories WHERE org_id = $1 AND project_id = $2
`

type UnlinkRepositoryParams struct {
	OrgID     string
	ProjectID string
}

func (q *Queries) UnlinkRepository(ctx context.Context, arg UnlinkRepositoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkRepository, arg.OrgID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
