// SPDX-License-Identifier: Apache-2.0

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leases.sql

package db

import (
	"context"
	"time"
)

const acquireLease = `-- name: AcquireLease :execrows
UPDATE jobs
SET status = 'running',
    runner_id = $1,
    lease_id = $2,
    lease_expires_at = $3,
    attempt = attempt + 1,
    -- Each attempt has its own log (ADR-0007 §1).
    log_bytes = 0,
    log_truncated = false,
    started_at = $4,
    cancel_requested = false
WHERE jobs.org_id = $5 AND jobs.id = $6 AND jobs.status = 'queued'
  AND EXISTS (
      SELECT 1 FROM runners r
      WHERE r.org_id = jobs.org_id AND r.id = $1 AND r.revoked_at IS NULL
        AND jobs.labels <@ r.labels
        AND (jobs.trusted OR NOT r.trusted)
        AND (SELECT count(*) FROM jobs held
             WHERE held.org_id = r.org_id AND held.runner_id = r.id AND held.status = 'running') < r.capacity
  )
`

type AcquireLeaseParams struct {
	RunnerID       *string
	LeaseID        []byte
	LeaseExpiresAt *time.Time
	Now            *time.Time
	OrgID          string
	ID             string
}

// AcquireLease re-checks the runner against its current row at grant time:
// it must not be revoked, must still have the job's labels and trust, and
// must be below its capacity (a long-polling Lease call must not outlive a
// revocation).
func (q *Queries) AcquireLease(ctx context.Context, arg AcquireLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, acquireLease,
		arg.RunnerID,
		arg.LeaseID,
		arg.LeaseExpiresAt,
		arg.Now,
		arg.OrgID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeLeasedJob = `-- name: CompleteLeasedJob :execrows
UPDATE jobs
SET status = $1,
    lease_id = NULL,
    lease_expires_at = NULL,
    exit_code = $2,
    failure_reason = $3,
    finished_at = $4
WHERE org_id = $5 AND id = $6 AND status = 'running'
  AND runner_id = $7 AND lease_id = $8
  AND lease_expires_at > $4
`

type CompleteLeasedJobParams struct {
	ToStatus      string
	ExitCode      *int32
	FailureReason string
	Now           *time.Time
	OrgID         string
	ID            string
	RunnerID      *string
	LeaseID       []byte
}

func (q *Queries) CompleteLeasedJob(ctx context.Context, arg CompleteLeasedJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeLeasedJob,
		arg.ToStatus,
		arg.ExitCode,
		arg.FailureReason,
		arg.Now,
		arg.OrgID,
		arg.ID,
		arg.RunnerID,
		arg.LeaseID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failExpiredJob = `-- name: FailExpiredJob :execrows
UPDATE jobs
SET status = $1, lease_id = NULL, lease_expires_at = NULL,
    failure_reason = $2, finished_at = $3
WHERE org_id = $4 AND id = $5 AND status = 'running'
  AND (lease_expires_at <= $3
       OR started_at + make_interval(secs => timeout_seconds + $6::integer) <= $3)
`

type FailExpiredJobParams struct {
	ToStatus      string
	FailureReason string
	Now           *time.Time
	OrgID         string
	ID            string
	GraceSeconds  int32
}

// FailExpiredJob ends a job whose lease lapsed with no attempts left, that
// was being canceled, or that exceeded its timeout.
func (q *Queries) FailExpiredJob(ctx context.Context, arg FailExpiredJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, failExpiredJob,
		arg.ToStatus,
		arg.FailureReason,
		arg.Now,
		arg.OrgID,
		arg.ID,
		arg.GraceSeconds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLeasedJob = `-- name: GetLeasedJob :one
SELECT id, org_id, run_id, name, status, needs, image, labels, steps, env, timeout_seconds, attempt,
    max_attempts, trusted, runner_id, cancel_requested, exit_code, failure_reason, created_at,
    queued_at, started_at, finished_at, lease_expires_at
FROM jobs
WHERE org_id = $1 AND id = $2 AND status = 'running'
  AND runner_id = $3 AND lease_id = $4
  AND lease_expires_at > $5
`

type GetLeasedJobParams struct {
	OrgID    string
	ID       string
	RunnerID *string
	LeaseID  []byte
	Now      *time.Time
}

type GetLeasedJobRow struct {
	ID              string
	OrgID           string
	RunID           string
	Name            string
	Status          string
	Needs           []string
	Image           string
	Labels          []string
	Steps           []byte
	Env             []byte
	TimeoutSeconds  int32
	Attempt         int32
	MaxAttempts     int32
	Trusted         bool
	RunnerID        *string
	CancelRequested bool
	ExitCode        *int32
	FailureReason   string
	CreatedAt       time.Time
	QueuedAt        *time.Time
	StartedAt       *time.Time
	FinishedAt      *time.Time
	LeaseExpiresAt  *time.Time
}

func (q *Queries) GetLeasedJob(ctx context.Context, arg GetLeasedJobParams) (GetLeasedJobRow, error) {
	row := q.db.QueryRow(ctx, getLeasedJob,
		arg.OrgID,
		arg.ID,
		arg.RunnerID,
		arg.LeaseID,
		arg.Now,
	)
	var i GetLeasedJobRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RunID,
		&i.Name,
		&i.Status,
		&i.Needs,
		&i.Image,
		&i.Labels,
		&i.Steps,
		&i.Env,
		&i.TimeoutSeconds,
		&i.Attempt,
		&i.MaxAttempts,
		&i.Trusted,
		&i.RunnerID,
		&i.CancelRequested,
		&i.ExitCode,
		&i.FailureReason,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LeaseExpiresAt,
	)
	return i, err
}

const listExpiredLeases = `-- name: ListExpiredLeases :many
SELECT id, org_id, run_id
FROM jobs
WHERE status = 'running'
  AND (lease_expires_at <= $1
       OR started_at + make_interval(secs => timeout_seconds + $2::integer) <= $1)
ORDER BY lease_expires_at
LIMIT $3
`

type ListExpiredLeasesParams struct {
	Now          *time.Time
	GraceSeconds int32
	MaxRows      int32
}

type ListExpiredLeasesRow struct {
	ID    string
	OrgID string
	RunID string
}

// ListExpiredLeases finds running jobs whose lease lapsed or whose hard
// timeout (plus grace) passed, across all orgs, for the reaper.
func (q *Queries) ListExpiredLeases(ctx context.Context, arg ListExpiredLeasesParams) ([]ListExpiredLeasesRow, error) {
	rows, err := q.db.Query(ctx, listExpiredLeases, arg.Now, arg.GraceSeconds, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredLeasesRow{}
	for rows.Next() {
		var i ListExpiredLeasesRow
		if err := rows.Scan(&i.ID, &i.OrgID, &i.RunID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaseCandidates = `-- name: ListLeaseCandidates :many

SELECT id, run_id
FROM jobs
WHERE org_id = $1
  AND status = 'queued'
  AND labels <@ $2::text[]
  -- A trusted runner never takes an untrusted job (fork PRs, ADR-0005 §9).
  AND (trusted OR NOT $3::boolean)
ORDER BY queued_at, id
LIMIT $4
`

type ListLeaseCandidatesParams struct {
	OrgID         string
	RunnerLabels  []string
	RunnerTrusted bool
	MaxRows       int32
}

type ListLeaseCandidatesRow struct {
	ID    string
	RunID string
}

// SPDX-License-Identifier: Apache-2.0
//
// Job leases (ADR-0005 §7). Lock order is always run row, then job row:
// callers find a candidate without locking, lock its run, then apply a
// compare-and-swap on the job. Every lease-bound change requires the lease
// ID, the leasing runner, and an unexpired lease.
func (q *Queries) ListLeaseCandidates(ctx context.Context, arg ListLeaseCandidatesParams) ([]ListLeaseCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listLeaseCandidates,
		arg.OrgID,
		arg.RunnerLabels,
		arg.RunnerTrusted,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeaseCandidatesRow{}
	for rows.Next() {
		var i ListLeaseCandidatesRow
		if err := rows.Scan(&i.ID, &i.RunID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRunnerForLease = `-- name: LockRunnerForLease :one
SELECT id FROM runners
WHERE org_id = $1 AND id = $2
FOR NO KEY UPDATE
`

type LockRunnerForLeaseParams struct {
	OrgID string
	ID    string
}

// LockRunnerForLease serializes lease grants per runner so the capacity
// check in AcquireLease cannot be raced. Lock order: run, runner, job.
func (q *Queries) LockRunnerForLease(ctx context.Context, arg LockRunnerForLeaseParams) (string, error) {
	row := q.db.QueryRow(ctx, lockRunnerForLease, arg.OrgID, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const releaseLease = `-- name: ReleaseLease :execrows
UPDATE jobs
SET status = 'queued', lease_id = NULL, lease_expires_at = NULL, runner_id = NULL,
    attempt = attempt - 1, started_at = NULL, queued_at = $1
WHERE org_id = $2 AND id = $3 AND status = 'running'
  AND runner_id = $4 AND lease_id = $5 AND attempt > 0
`

type ReleaseLeaseParams struct {
	Now      *time.Time
	OrgID    string
	ID       string
	RunnerID *string
	LeaseID  []byte
}

// ReleaseLease puts a job that was leased but never delivered back in the
// queue without spending an attempt.
func (q *Queries) ReleaseLease(ctx context.Context, arg ReleaseLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseLease,
		arg.Now,
		arg.OrgID,
		arg.ID,
		arg.RunnerID,
		arg.LeaseID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewLease = `-- name: RenewLease :one
UPDATE jobs
SET lease_expires_at = $1
WHERE org_id = $2 AND id = $3 AND status = 'running'
  AND runner_id = $4 AND lease_id = $5
  AND lease_expires_at > $6
RETURNING cancel_requested, started_at, timeout_seconds
`

type RenewLeaseParams struct {
	LeaseExpiresAt *time.Time
	OrgID          string
	ID             string
	RunnerID       *string
	LeaseID        []byte
	Now            *time.Time
}

type RenewLeaseRow struct {
	CancelRequested bool
	StartedAt       *time.Time
	TimeoutSeconds  int32
}

func (q *Queries) RenewLease(ctx context.Context, arg RenewLeaseParams) (RenewLeaseRow, error) {
	row := q.db.QueryRow(ctx, renewLease,
		arg.LeaseExpiresAt,
		arg.OrgID,
		arg.ID,
		arg.RunnerID,
		arg.LeaseID,
		arg.Now,
	)
	var i RenewLeaseRow
	err := row.Scan(&i.CancelRequested, &i.StartedAt, &i.TimeoutSeconds)
	return i, err
}

const requeueExpiredJob = `-- name: RequeueExpiredJob :execrows
UPDATE jobs
SET status = 'queued', lease_id = NULL, lease_expires_at = NULL, runner_id = NULL,
    queued_at = $1, started_at = NULL
WHERE org_id = $2 AND id = $3 AND status = 'running'
  AND lease_expires_at <= $1 AND attempt < max_attempts AND NOT cancel_requested
  AND started_at + make_interval(secs => timeout_seconds) > $1
`

type RequeueExpiredJobParams struct {
	Now   *time.Time
	OrgID string
	ID    string
}

// RequeueExpiredJob gives a job whose lease lapsed another attempt.
func (q *Queries) RequeueExpiredJob(ctx context.Context, arg RequeueExpiredJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, requeueExpiredJob, arg.Now, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
