// SPDX-License-Identifier: Apache-2.0

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: logs.sql

package db

import (
	"context"
	"time"
)

const addJobLogBytes = `-- name: AddJobLogBytes :exec
UPDATE jobs
SET log_bytes = log_bytes + $1::bigint, log_truncated = log_truncated OR $2::boolean
WHERE org_id = $3 AND id = $4
`

type AddJobLogBytesParams struct {
	Added     int64
	Truncated bool
	OrgID     string
	ID        string
}

func (q *Queries) AddJobLogBytes(ctx context.Context, arg AddJobLogBytesParams) error {
	_, err := q.db.Exec(ctx, addJobLogBytes,
		arg.Added,
		arg.Truncated,
		arg.OrgID,
		arg.ID,
	)
	return err
}

const getJobLogChunk = `-- name: GetJobLogChunk :one
SELECT seq, size, sha256, sha256_request, object_key
FROM job_log_chunks
WHERE org_id = $1 AND job_id = $2 AND attempt = $3 AND seq = $4
`

type GetJobLogChunkParams struct {
	OrgID   string
	JobID   string
	Attempt int32
	Seq     int32
}

type GetJobLogChunkRow struct {
	Seq           int32
	Size          int32
	Sha256        []byte
	Sha256Request []byte
	ObjectKey     string
}

func (q *Queries) GetJobLogChunk(ctx context.Context, arg GetJobLogChunkParams) (GetJobLogChunkRow, error) {
	row := q.db.QueryRow(ctx, getJobLogChunk,
		arg.OrgID,
		arg.JobID,
		arg.Attempt,
		arg.Seq,
	)
	var i GetJobLogChunkRow
	err := row.Scan(
		&i.Seq,
		&i.Size,
		&i.Sha256,
		&i.Sha256Request,
		&i.ObjectKey,
	)
	return i, err
}

const getRunJob = `-- name: GetRunJob :one
SELECT j.id, j.org_id, j.run_id, j.name, j.status, j.attempt, j.log_bytes, j.log_truncated
FROM jobs j
JOIN runs r ON r.org_id = j.org_id AND r.id = j.run_id
WHERE j.org_id = $1 AND r.project_id = $2
  AND j.run_id = $3 AND j.id = $4
`

type GetRunJobParams struct {
	OrgID     string
	ProjectID string
	RunID     string
	JobID     string
}

type GetRunJobRow struct {
	ID           string
	OrgID        string
	RunID        string
	Name         string
	Status       string
	Attempt      int32
	LogBytes     int64
	LogTruncated bool
}

// GetRunJob finds a job through its run and project, for authorization.
func (q *Queries) GetRunJob(ctx context.Context, arg GetRunJobParams) (GetRunJobRow, error) {
	row := q.db.QueryRow(ctx, getRunJob,
		arg.OrgID,
		arg.ProjectID,
		arg.RunID,
		arg.JobID,
	)
	var i GetRunJobRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RunID,
		&i.Name,
		&i.Status,
		&i.Attempt,
		&i.LogBytes,
		&i.LogTruncated,
	)
	return i, err
}

const insertJobLogChunk = `-- name: InsertJobLogChunk :exec
INSERT INTO job_log_chunks (org_id, job_id, attempt, seq, size, sha256, sha256_request, object_key, runner_id, lease_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertJobLogChunkParams struct {
	OrgID         string
	JobID         string
	Attempt       int32
	Seq           int32
	Size          int32
	Sha256        []byte
	Sha256Request []byte
	ObjectKey     string
	RunnerID      *string
	LeaseID       []byte
	CreatedAt     time.Time
}

func (q *Queries) InsertJobLogChunk(ctx context.Context, arg InsertJobLogChunkParams) error {
	_, err := q.db.Exec(ctx, insertJobLogChunk,
		arg.OrgID,
		arg.JobID,
		arg.Attempt,
		arg.Seq,
		arg.Size,
		arg.Sha256,
		arg.Sha256Request,
		arg.ObjectKey,
		arg.RunnerID,
		arg.LeaseID,
		arg.CreatedAt,
	)
	return err
}

const listJobLogChunks = `-- name: ListJobLogChunks :many
SELECT seq, size, object_key
FROM job_log_chunks
WHERE org_id = $1 AND job_id = $2 AND attempt = $3
  AND seq >= $4
ORDER BY seq
LIMIT $5
`

type ListJobLogChunksParams struct {
	OrgID   string
	JobID   string
	Attempt int32
	FromSeq int32
	MaxRows int32
}

type ListJobLogChunksRow struct {
	Seq       int32
	Size      int32
	ObjectKey string
}

func (q *Queries) ListJobLogChunks(ctx context.Context, arg ListJobLogChunksParams) ([]ListJobLogChunksRow, error) {
	rows, err := q.db.Query(ctx, listJobLogChunks,
		arg.OrgID,
		arg.JobID,
		arg.Attempt,
		arg.FromSeq,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobLogChunksRow{}
	for rows.Next() {
		var i ListJobLogChunksRow
		if err := rows.Scan(&i.Seq, &i.Size, &i.ObjectKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockJobLogState = `-- name: LockJobLogState :one

SELECT j.run_id, j.attempt, j.log_bytes, j.log_truncated,
    (SELECT count(*) FROM job_log_chunks c
     WHERE c.org_id = j.org_id AND c.job_id = j.id AND c.attempt = j.attempt)::integer AS chunks
FROM jobs j
WHERE j.org_id = $1 AND j.id = $2 AND j.status = 'running'
  AND j.runner_id = $3 AND j.lease_id = $4
  AND j.lease_expires_at > $5
FOR UPDATE OF j
`

type LockJobLogStateParams struct {
	OrgID    string
	ID       string
	RunnerID *string
	LeaseID  []byte
	Now      *time.Time
}

type LockJobLogStateRow struct {
	RunID        string
	Attempt      int32
	LogBytes     int64
	LogTruncated bool
	Chunks       int32
}

// SPDX-License-Identifier: Apache-2.0
// LockJobLogState serializes appends for one job and re-checks the lease
// under the row lock, so a runner whose lease lapsed (and was re-leased)
// cannot append between a check and the insert. Log bytes and the chunk
// count are those of the current attempt.
func (q *Queries) LockJobLogState(ctx context.Context, arg LockJobLogStateParams) (LockJobLogStateRow, error) {
	row := q.db.QueryRow(ctx, lockJobLogState,
		arg.OrgID,
		arg.ID,
		arg.RunnerID,
		arg.LeaseID,
		arg.Now,
	)
	var i LockJobLogStateRow
	err := row.Scan(
		&i.RunID,
		&i.Attempt,
		&i.LogBytes,
		&i.LogTruncated,
		&i.Chunks,
	)
	return i, err
}
