// SPDX-License-Identifier: Apache-2.0

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type ApiToken struct {
	ID         string
	UserID     string
	Name       string
	Prefix     string
	TokenHash  []byte
	Scopes     []string
	CreatedAt  time.Time
	ExpiresAt  time.Time
	LastUsedAt *time.Time
	RevokedAt  *time.Time
}

type AuditEvent struct {
	ID         string
	ChainKey   string
	Seq        int64
	OrgID      *string
	OccurredAt time.Time
	ActorKind  string
	ActorID    string
	Action     string
	TargetType string
	TargetID   string
	Result     string
	RequestID  string
	SourceIp   string
	UserAgent  string
	Details    []byte
	PrevHash   []byte
	Hash       []byte
}

type DesktopAccessToken struct {
	TokenHash []byte
	GrantID   string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type DesktopAuthCode struct {
	CodeHash      []byte
	UserID        string
	CodeChallenge string
	RedirectUri   string
	CreatedAt     time.Time
	ExpiresAt     time.Time
	UsedAt        *time.Time
}

type DesktopGrant struct {
	ID        string
	UserID    string
	CreatedAt time.Time
	ExpiresAt time.Time
	RevokedAt *time.Time
}

type DesktopRefreshToken struct {
	TokenHash []byte
	GrantID   string
	CreatedAt time.Time
	ExpiresAt time.Time
	UsedAt    *time.Time
}

type LoginState struct {
	StateHash            []byte
	Client               string
	Nonce                string
	IdpCodeVerifier      string
	ReturnTo             string
	DesktopRedirectUri   string
	DesktopCodeChallenge string
	DesktopState         string
	CreatedAt            time.Time
	ExpiresAt            time.Time
}

type Membership struct {
	OrgID     string
	UserID    string
	Role      string
	CreatedAt time.Time
}

type Org struct {
	ID        string
	Slug      string
	Name      string
	CreatedAt time.Time
}

type Project struct {
	ID        string
	OrgID     string
	Slug      string
	Name      string
	CreatedAt time.Time
}

type User struct {
	ID            string
	OidcIssuer    *string
	OidcSubject   *string
	Email         string
	DisplayName   string
	InstanceAdmin bool
	CreatedAt     time.Time
}

type WebSession struct {
	ID         string
	TokenHash  []byte
	UserID     string
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
	RevokedAt  *time.Time
}
