// SPDX-License-Identifier: Apache-2.0

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs.sql

package db

import (
	"context"
	"time"
)

const addMembership = `-- name: AddMembership :exec
INSERT INTO memberships (org_id, user_id, role, created_at)
VALUES ($1, $2, $3, $4)
`

type AddMembershipParams struct {
	OrgID     string
	UserID    string
	Role      string
	CreatedAt time.Time
}

func (q *Queries) AddMembership(ctx context.Context, arg AddMembershipParams) error {
	_, err := q.db.Exec(ctx, addMembership,
		arg.OrgID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const createOrg = `-- name: CreateOrg :one

INSERT INTO orgs (id, slug, name, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, slug, name, created_at
`

type CreateOrgParams struct {
	ID        string
	Slug      string
	Name      string
	CreatedAt time.Time
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, createOrg,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.CreatedAt,
	)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :execrows
DELETE FROM memberships
WHERE org_id = $1 AND user_id = $2
`

type DeleteMembershipParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMembership, arg.OrgID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMember = `-- name: GetMember :one
SELECT m.user_id, u.email, u.display_name, m.role
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.org_id = $1 AND m.user_id = $2
`

type GetMemberParams struct {
	OrgID  string
	UserID string
}

type GetMemberRow struct {
	UserID      string
	Email       string
	DisplayName string
	Role        string
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (GetMemberRow, error) {
	row := q.db.QueryRow(ctx, getMember, arg.OrgID, arg.UserID)
	var i GetMemberRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
	)
	return i, err
}

const getMembershipRole = `-- name: GetMembershipRole :one
SELECT role FROM memberships
WHERE org_id = $1 AND user_id = $2
`

type GetMembershipRoleParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) GetMembershipRole(ctx context.Context, arg GetMembershipRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMembershipRole, arg.OrgID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getOrgBySlug = `-- name: GetOrgBySlug :one
SELECT id, slug, name, created_at FROM orgs WHERE slug = $1
`

// GetOrgBySlug is for instance-admin operations only (no membership check).
func (q *Queries) GetOrgBySlug(ctx context.Context, slug string) (Org, error) {
	row := q.db.QueryRow(ctx, getOrgBySlug, slug)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgForMember = `-- name: GetOrgForMember :one
SELECT o.id, o.slug, o.name, o.created_at, m.role
FROM orgs o
JOIN memberships m ON m.org_id = o.id
WHERE o.slug = $1 AND m.user_id = $2
`

type GetOrgForMemberParams struct {
	Slug   string
	UserID string
}

type GetOrgForMemberRow struct {
	ID        string
	Slug      string
	Name      string
	CreatedAt time.Time
	Role      string
}

// GetOrgForMember is the tenant-scoped org lookup: it returns a row only when
// the user is a member, so non-members cannot tell "exists" from "not found".
func (q *Queries) GetOrgForMember(ctx context.Context, arg GetOrgForMemberParams) (GetOrgForMemberRow, error) {
	row := q.db.QueryRow(ctx, getOrgForMember, arg.Slug, arg.UserID)
	var i GetOrgForMemberRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT m.user_id, u.email, u.display_name, m.role
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.org_id = $1 AND m.user_id > $2
ORDER BY m.user_id
LIMIT $3
`

type ListMembersParams struct {
	OrgID       string
	AfterUserID string
	MaxRows     int32
}

type ListMembersRow struct {
	UserID      string
	Email       string
	DisplayName string
	Role        string
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, arg.OrgID, arg.AfterUserID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgsForMember = `-- name: ListOrgsForMember :many
SELECT o.id, o.slug, o.name, o.created_at, m.role
FROM orgs o
JOIN memberships m ON m.org_id = o.id
WHERE m.user_id = $1 AND o.id > $2
ORDER BY o.id
LIMIT $3
`

type ListOrgsForMemberParams struct {
	UserID  string
	AfterID string
	MaxRows int32
}

type ListOrgsForMemberRow struct {
	ID        string
	Slug      string
	Name      string
	CreatedAt time.Time
	Role      string
}

func (q *Queries) ListOrgsForMember(ctx context.Context, arg ListOrgsForMemberParams) ([]ListOrgsForMemberRow, error) {
	rows, err := q.db.Query(ctx, listOrgsForMember, arg.UserID, arg.AfterID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgsForMemberRow{}
	for rows.Next() {
		var i ListOrgsForMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOwners = `-- name: LockOwners :many
SELECT user_id FROM memberships
WHERE org_id = $1 AND role = 'owner'
ORDER BY user_id
FOR UPDATE
`

// LockOwners locks the org's owner rows so "last owner" checks are race-free.
func (q *Queries) LockOwners(ctx context.Context, orgID string) ([]string, error) {
	rows, err := q.db.Query(ctx, lockOwners, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembershipRole = `-- name: UpdateMembershipRole :execrows
UPDATE memberships SET role = $3
WHERE org_id = $1 AND user_id = $2
`

type UpdateMembershipRoleParams struct {
	OrgID  string
	UserID string
	Role   string
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMembershipRole, arg.OrgID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
