// SPDX-License-Identifier: Apache-2.0

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
	"time"
)

const createProject = `-- name: CreateProject :one

INSERT INTO projects (id, org_id, slug, name, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, slug, name, created_at
`

type CreateProjectParams struct {
	ID        string
	OrgID     string
	Slug      string
	Name      string
	CreatedAt time.Time
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.OrgID,
		arg.Slug,
		arg.Name,
		arg.CreatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, org_id, slug, name, created_at
FROM projects
WHERE org_id = $1 AND slug = $2
`

type GetProjectParams struct {
	OrgID string
	Slug  string
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, arg.OrgID, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, org_id, slug, name, created_at
FROM projects
WHERE org_id = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListProjectsParams struct {
	OrgID   string
	AfterID string
	MaxRows int32
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.OrgID, arg.AfterID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
