// SPDX-License-Identifier: Apache-2.0

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runners.sql

package db

import (
	"context"
	"time"
)

const claimRunnerRegistrationToken = `-- name: ClaimRunnerRegistrationToken :one
SELECT id, org_id, labels, trusted, created_by
FROM runner_registration_tokens
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > $2
FOR UPDATE
`

type ClaimRunnerRegistrationTokenParams struct {
	TokenHash []byte
	Now       time.Time
}

type ClaimRunnerRegistrationTokenRow struct {
	ID        string
	OrgID     string
	Labels    []string
	Trusted   bool
	CreatedBy *string
}

// ClaimRunnerRegistrationToken locks an unused, unexpired token by hash.
func (q *Queries) ClaimRunnerRegistrationToken(ctx context.Context, arg ClaimRunnerRegistrationTokenParams) (ClaimRunnerRegistrationTokenRow, error) {
	row := q.db.QueryRow(ctx, claimRunnerRegistrationToken, arg.TokenHash, arg.Now)
	var i ClaimRunnerRegistrationTokenRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Labels,
		&i.Trusted,
		&i.CreatedBy,
	)
	return i, err
}

const countActiveRunnerRegistrationTokens = `-- name: CountActiveRunnerRegistrationTokens :one
SELECT count(*) FROM runner_registration_tokens
WHERE org_id = $1 AND used_at IS NULL AND expires_at > $2
`

type CountActiveRunnerRegistrationTokensParams struct {
	OrgID     string
	ExpiresAt time.Time
}

func (q *Queries) CountActiveRunnerRegistrationTokens(ctx context.Context, arg CountActiveRunnerRegistrationTokensParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRunnerRegistrationTokens, arg.OrgID, arg.ExpiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRunner = `-- name: CreateRunner :exec
INSERT INTO runners (id, org_id, name, labels, trusted, version, cert_serial, cert_der, cert_spki_sha256,
    cert_renewed_at, cert_expires_at, created_by, created_at, last_seen_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type CreateRunnerParams struct {
	ID             string
	OrgID          string
	Name           string
	Labels         []string
	Trusted        bool
	Version        string
	CertSerial     string
	CertDer        []byte
	CertSpkiSha256 []byte
	CertRenewedAt  time.Time
	CertExpiresAt  time.Time
	CreatedBy      *string
	CreatedAt      time.Time
	LastSeenAt     *time.Time
}

func (q *Queries) CreateRunner(ctx context.Context, arg CreateRunnerParams) error {
	_, err := q.db.Exec(ctx, createRunner,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Labels,
		arg.Trusted,
		arg.Version,
		arg.CertSerial,
		arg.CertDer,
		arg.CertSpkiSha256,
		arg.CertRenewedAt,
		arg.CertExpiresAt,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.LastSeenAt,
	)
	return err
}

const createRunnerRegistrationToken = `-- name: CreateRunnerRegistrationToken :exec

INSERT INTO runner_registration_tokens (id, org_id, token_hash, labels, trusted, created_by, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateRunnerRegistrationTokenParams struct {
	ID        string
	OrgID     string
	TokenHash []byte
	Labels    []string
	Trusted   bool
	CreatedBy *string
	CreatedAt time.Time
	ExpiresAt time.Time
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) CreateRunnerRegistrationToken(ctx context.Context, arg CreateRunnerRegistrationTokenParams) error {
	_, err := q.db.Exec(ctx, createRunnerRegistrationToken,
		arg.ID,
		arg.OrgID,
		arg.TokenHash,
		arg.Labels,
		arg.Trusted,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredRunnerRegistrationTokens = `-- name: DeleteExpiredRunnerRegistrationTokens :execrows
DELETE FROM runner_registration_tokens
WHERE used_at IS NULL AND expires_at <= $1
`

func (q *Queries) DeleteExpiredRunnerRegistrationTokens(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRunnerRegistrationTokens, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRunner = `-- name: GetRunner :one
SELECT id, org_id, name, labels, trusted, version, capacity, cert_serial, cert_der, cert_spki_sha256,
    prev_cert_serial, cert_renewed_at, cert_expires_at, created_by, created_at, last_seen_at, revoked_at
FROM runners
WHERE org_id = $1 AND id = $2
`

type GetRunnerParams struct {
	OrgID string
	ID    string
}

func (q *Queries) GetRunner(ctx context.Context, arg GetRunnerParams) (Runner, error) {
	row := q.db.QueryRow(ctx, getRunner, arg.OrgID, arg.ID)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Labels,
		&i.Trusted,
		&i.Version,
		&i.Capacity,
		&i.CertSerial,
		&i.CertDer,
		&i.CertSpkiSha256,
		&i.PrevCertSerial,
		&i.CertRenewedAt,
		&i.CertExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const listRunners = `-- name: ListRunners :many
SELECT id, org_id, name, labels, trusted, version, capacity, cert_serial, cert_der, cert_spki_sha256,
    prev_cert_serial, cert_renewed_at, cert_expires_at, created_by, created_at, last_seen_at, revoked_at
FROM runners
WHERE org_id = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListRunnersParams struct {
	OrgID   string
	AfterID string
	MaxRows int32
}

func (q *Queries) ListRunners(ctx context.Context, arg ListRunnersParams) ([]Runner, error) {
	rows, err := q.db.Query(ctx, listRunners, arg.OrgID, arg.AfterID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Runner{}
	for rows.Next() {
		var i Runner
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Labels,
			&i.Trusted,
			&i.Version,
			&i.Capacity,
			&i.CertSerial,
			&i.CertDer,
			&i.CertSpkiSha256,
			&i.PrevCertSerial,
			&i.CertRenewedAt,
			&i.CertExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRunner = `-- name: LockRunner :one
SELECT id, org_id, name, labels, trusted, version, capacity, cert_serial, cert_der, cert_spki_sha256,
    prev_cert_serial, cert_renewed_at, cert_expires_at, created_by, created_at, last_seen_at, revoked_at
FROM runners
WHERE org_id = $1 AND id = $2
FOR UPDATE
`

type LockRunnerParams struct {
	OrgID string
	ID    string
}

func (q *Queries) LockRunner(ctx context.Context, arg LockRunnerParams) (Runner, error) {
	row := q.db.QueryRow(ctx, lockRunner, arg.OrgID, arg.ID)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Labels,
		&i.Trusted,
		&i.Version,
		&i.Capacity,
		&i.CertSerial,
		&i.CertDer,
		&i.CertSpkiSha256,
		&i.PrevCertSerial,
		&i.CertRenewedAt,
		&i.CertExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const markRunnerRegistrationTokenUsed = `-- name: MarkRunnerRegistrationTokenUsed :execrows
UPDATE runner_registration_tokens
SET used_at = $1, runner_id = $2
WHERE id = $3 AND used_at IS NULL
`

type MarkRunnerRegistrationTokenUsedParams struct {
	Now      *time.Time
	RunnerID *string
	ID       string
}

func (q *Queries) MarkRunnerRegistrationTokenUsed(ctx context.Context, arg MarkRunnerRegistrationTokenUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRunnerRegistrationTokenUsed, arg.Now, arg.RunnerID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRunner = `-- name: RevokeRunner :execrows
UPDATE runners
SET revoked_at = $1
WHERE org_id = $2 AND id = $3 AND revoked_at IS NULL
`

type RevokeRunnerParams struct {
	Now   *time.Time
	OrgID string
	ID    string
}

func (q *Queries) RevokeRunner(ctx context.Context, arg RevokeRunnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRunner, arg.Now, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateRunnerCertificate = `-- name: RotateRunnerCertificate :execrows
UPDATE runners
SET prev_cert_serial = cert_serial, cert_serial = $1, cert_der = $2,
    cert_spki_sha256 = $3, cert_renewed_at = $4, cert_expires_at = $5
WHERE org_id = $6 AND id = $7 AND cert_serial = $8
  AND revoked_at IS NULL
`

type RotateRunnerCertificateParams struct {
	NewSerial      string
	CertDer        []byte
	CertSpkiSha256 []byte
	Now            time.Time
	ExpiresAt      time.Time
	OrgID          string
	ID             string
	CurrentSerial  string
}

// RotateRunnerCertificate records a renewal from the current serial.
func (q *Queries) RotateRunnerCertificate(ctx context.Context, arg RotateRunnerCertificateParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateRunnerCertificate,
		arg.NewSerial,
		arg.CertDer,
		arg.CertSpkiSha256,
		arg.Now,
		arg.ExpiresAt,
		arg.OrgID,
		arg.ID,
		arg.CurrentSerial,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchRunner = `-- name: TouchRunner :exec
UPDATE runners
SET last_seen_at = $1
WHERE org_id = $2 AND id = $3
  AND (last_seen_at IS NULL OR last_seen_at < $1::timestamptz - interval '1 minute')
`

type TouchRunnerParams struct {
	Now   *time.Time
	OrgID string
	ID    string
}

// TouchRunner records activity at most once a minute per runner.
func (q *Queries) TouchRunner(ctx context.Context, arg TouchRunnerParams) error {
	_, err := q.db.Exec(ctx, touchRunner, arg.Now, arg.OrgID, arg.ID)
	return err
}
