// SPDX-License-Identifier: Apache-2.0

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package db

import (
	"context"
	"time"
)

const createJob = `-- name: CreateJob :exec
INSERT INTO jobs (id, org_id, run_id, name, status, needs, image, labels, steps, env,
    timeout_seconds, attempt, max_attempts, trusted, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type CreateJobParams struct {
	ID             string
	OrgID          string
	RunID          string
	Name           string
	Status         string
	Needs          []string
	Image          string
	Labels         []string
	Steps          []byte
	Env            []byte
	TimeoutSeconds int32
	Attempt        int32
	MaxAttempts    int32
	Trusted        bool
	CreatedAt      time.Time
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.Exec(ctx, createJob,
		arg.ID,
		arg.OrgID,
		arg.RunID,
		arg.Name,
		arg.Status,
		arg.Needs,
		arg.Image,
		arg.Labels,
		arg.Steps,
		arg.Env,
		arg.TimeoutSeconds,
		arg.Attempt,
		arg.MaxAttempts,
		arg.Trusted,
		arg.CreatedAt,
	)
	return err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (id, org_id, project_id, number, status, event, ref, branch, commit_sha, title,
    pr_number, is_fork, trusted, actor_login, created_by, idempotency_key, error, created_at,
    started_at, finished_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)
RETURNING id, org_id, project_id, number, status, event, ref, branch, commit_sha, title, pr_number,
    is_fork, trusted, actor_login, created_by, idempotency_key, error, created_at, started_at, finished_at
`

type CreateRunParams struct {
	ID             string
	OrgID          string
	ProjectID      string
	Number         int64
	Status         string
	Event          string
	Ref            string
	Branch         string
	CommitSha      string
	Title          string
	PrNumber       int32
	IsFork         bool
	Trusted        bool
	ActorLogin     string
	CreatedBy      *string
	IdempotencyKey *string
	Error          string
	CreatedAt      time.Time
	StartedAt      *time.Time
	FinishedAt     *time.Time
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.Number,
		arg.Status,
		arg.Event,
		arg.Ref,
		arg.Branch,
		arg.CommitSha,
		arg.Title,
		arg.PrNumber,
		arg.IsFork,
		arg.Trusted,
		arg.ActorLogin,
		arg.CreatedBy,
		arg.IdempotencyKey,
		arg.Error,
		arg.CreatedAt,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Number,
		&i.Status,
		&i.Event,
		&i.Ref,
		&i.Branch,
		&i.CommitSha,
		&i.Title,
		&i.PrNumber,
		&i.IsFork,
		&i.Trusted,
		&i.ActorLogin,
		&i.CreatedBy,
		&i.IdempotencyKey,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, org_id, project_id, number, status, event, ref, branch, commit_sha, title, pr_number,
    is_fork, trusted, actor_login, created_by, idempotency_key, error, created_at, started_at, finished_at
FROM runs
WHERE org_id = $1 AND project_id = $2 AND id = $3
`

type GetRunParams struct {
	OrgID     string
	ProjectID string
	ID        string
}

func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, arg.OrgID, arg.ProjectID, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Number,
		&i.Status,
		&i.Event,
		&i.Ref,
		&i.Branch,
		&i.CommitSha,
		&i.Title,
		&i.PrNumber,
		&i.IsFork,
		&i.Trusted,
		&i.ActorLogin,
		&i.CreatedBy,
		&i.IdempotencyKey,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getRunByIdempotencyKey = `-- name: GetRunByIdempotencyKey :one
SELECT id, org_id, project_id, number, status, event, ref, branch, commit_sha, title, pr_number,
    is_fork, trusted, actor_login, created_by, idempotency_key, error, created_at, started_at, finished_at
FROM runs
WHERE org_id = $1 AND project_id = $2 AND idempotency_key = $3
`

type GetRunByIdempotencyKeyParams struct {
	OrgID          string
	ProjectID      string
	IdempotencyKey *string
}

func (q *Queries) GetRunByIdempotencyKey(ctx context.Context, arg GetRunByIdempotencyKeyParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRunByIdempotencyKey, arg.OrgID, arg.ProjectID, arg.IdempotencyKey)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Number,
		&i.Status,
		&i.Event,
		&i.Ref,
		&i.Branch,
		&i.CommitSha,
		&i.Title,
		&i.PrNumber,
		&i.IsFork,
		&i.Trusted,
		&i.ActorLogin,
		&i.CreatedBy,
		&i.IdempotencyKey,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, org_id, run_id, name, status, needs, image, labels, steps, env, timeout_seconds, attempt,
    max_attempts, trusted, runner_id, cancel_requested, exit_code, failure_reason, created_at,
    queued_at, started_at, finished_at
FROM jobs
WHERE org_id = $1 AND run_id = $2
ORDER BY id
`

type ListJobsParams struct {
	OrgID string
	RunID string
}

type ListJobsRow struct {
	ID              string
	OrgID           string
	RunID           string
	Name            string
	Status          string
	Needs           []string
	Image           string
	Labels          []string
	Steps           []byte
	Env             []byte
	TimeoutSeconds  int32
	Attempt         int32
	MaxAttempts     int32
	Trusted         bool
	RunnerID        *string
	CancelRequested bool
	ExitCode        *int32
	FailureReason   string
	CreatedAt       time.Time
	QueuedAt        *time.Time
	StartedAt       *time.Time
	FinishedAt      *time.Time
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]ListJobsRow, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.OrgID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsRow{}
	for rows.Next() {
		var i ListJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RunID,
			&i.Name,
			&i.Status,
			&i.Needs,
			&i.Image,
			&i.Labels,
			&i.Steps,
			&i.Env,
			&i.TimeoutSeconds,
			&i.Attempt,
			&i.MaxAttempts,
			&i.Trusted,
			&i.RunnerID,
			&i.CancelRequested,
			&i.ExitCode,
			&i.FailureReason,
			&i.CreatedAt,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, org_id, project_id, number, status, event, ref, branch, commit_sha, title, pr_number,
    is_fork, trusted, actor_login, created_by, idempotency_key, error, created_at, started_at, finished_at
FROM runs
WHERE org_id = $1 AND project_id = $2
  AND ($3::text = '' OR id < $3::text)
ORDER BY id DESC
LIMIT $4
`

type ListRunsParams struct {
	OrgID     string
	ProjectID string
	BeforeID  string
	MaxRows   int32
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRuns,
		arg.OrgID,
		arg.ProjectID,
		arg.BeforeID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Number,
			&i.Status,
			&i.Event,
			&i.Ref,
			&i.Branch,
			&i.CommitSha,
			&i.Title,
			&i.PrNumber,
			&i.IsFork,
			&i.Trusted,
			&i.ActorLogin,
			&i.CreatedBy,
			&i.IdempotencyKey,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRun = `-- name: LockRun :one
SELECT id, org_id, project_id, number, status, event, ref, branch, commit_sha, title, pr_number,
    is_fork, trusted, actor_login, created_by, idempotency_key, error, created_at, started_at, finished_at
FROM runs
WHERE org_id = $1 AND id = $2
FOR UPDATE
`

type LockRunParams struct {
	OrgID string
	ID    string
}

// LockRun locks a run row for the rest of the transaction.
func (q *Queries) LockRun(ctx context.Context, arg LockRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, lockRun, arg.OrgID, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Number,
		&i.Status,
		&i.Event,
		&i.Ref,
		&i.Branch,
		&i.CommitSha,
		&i.Title,
		&i.PrNumber,
		&i.IsFork,
		&i.Trusted,
		&i.ActorLogin,
		&i.CreatedBy,
		&i.IdempotencyKey,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const nextRunNumber = `-- name: NextRunNumber :one

INSERT INTO project_run_counters (project_id, org_id, last_number)
VALUES ($1, $2, 1)
ON CONFLICT (project_id) DO UPDATE SET last_number = project_run_counters.last_number + 1
RETURNING last_number
`

type NextRunNumberParams struct {
	ProjectID string
	OrgID     string
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) NextRunNumber(ctx context.Context, arg NextRunNumberParams) (int64, error) {
	row := q.db.QueryRow(ctx, nextRunNumber, arg.ProjectID, arg.OrgID)
	var last_number int64
	err := row.Scan(&last_number)
	return last_number, err
}

const requestJobCancel = `-- name: RequestJobCancel :execrows
UPDATE jobs
SET cancel_requested = true
WHERE org_id = $1 AND id = $2 AND status = 'running'
`

type RequestJobCancelParams struct {
	OrgID string
	ID    string
}

func (q *Queries) RequestJobCancel(ctx context.Context, arg RequestJobCancelParams) (int64, error) {
	result, err := q.db.Exec(ctx, requestJobCancel, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateJobStatus = `-- name: UpdateJobStatus :execrows
UPDATE jobs
SET status = $1,
    queued_at = CASE WHEN $1::text = 'queued' THEN $2 ELSE queued_at END,
    finished_at = CASE WHEN $1::text IN ('succeeded', 'failed', 'canceled', 'skipped')
        THEN $2 ELSE finished_at END,
    failure_reason = CASE WHEN $3::text = '' THEN failure_reason ELSE $3::text END
WHERE org_id = $4 AND id = $5 AND status = $6
  AND status <> 'running'
`

type UpdateJobStatusParams struct {
	ToStatus      string
	At            *time.Time
	FailureReason string
	OrgID         string
	ID            string
	FromStatus    string
}

// UpdateJobStatus is a compare-and-swap on a job that is not leased (queued,
// pending, or being canceled/failed while queued). Leased jobs are changed
// only through the scheduler's lease-bound queries.
func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateJobStatus,
		arg.ToStatus,
		arg.At,
		arg.FailureReason,
		arg.OrgID,
		arg.ID,
		arg.FromStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRunStatus = `-- name: UpdateRunStatus :execrows
UPDATE runs
SET status = $1,
    started_at = COALESCE(started_at, $2),
    finished_at = COALESCE(finished_at, $3)
WHERE org_id = $4 AND id = $5 AND status = $6
`

type UpdateRunStatusParams struct {
	ToStatus   string
	StartedAt  *time.Time
	FinishedAt *time.Time
	OrgID      string
	ID         string
	FromStatus string
}

// UpdateRunStatus is a compare-and-swap: it changes nothing unless the run
// is still in from_status. Timestamps are set once and never cleared.
func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRunStatus,
		arg.ToStatus,
		arg.StartedAt,
		arg.FinishedAt,
		arg.OrgID,
		arg.ID,
		arg.FromStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
