// SPDX-License-Identifier: Apache-2.0

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package db

import (
	"context"
	"time"
)

const countSecretDataKeysNotWrappedBy = `-- name: CountSecretDataKeysNotWrappedBy :one
SELECT count(*) FROM secret_data_keys
WHERE NOT (key_id = ANY ($1::text[]))
`

func (q *Queries) CountSecretDataKeysNotWrappedBy(ctx context.Context, keyIds []string) (int64, error) {
	row := q.db.QueryRow(ctx, countSecretDataKeysNotWrappedBy, keyIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSecretsInScope = `-- name: CountSecretsInScope :one
SELECT count(*) FROM secrets
WHERE org_id = $1 AND project_id IS NOT DISTINCT FROM $2
`

type CountSecretsInScopeParams struct {
	OrgID     string
	ProjectID *string
}

func (q *Queries) CountSecretsInScope(ctx context.Context, arg CountSecretsInScopeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSecretsInScope, arg.OrgID, arg.ProjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSecret = `-- name: DeleteSecret :execrows
DELETE FROM secrets
WHERE org_id = $1 AND project_id IS NOT DISTINCT FROM $2 AND name = $3
`

type DeleteSecretParams struct {
	OrgID     string
	ProjectID *string
	Name      string
}

func (q *Queries) DeleteSecret(ctx context.Context, arg DeleteSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSecret, arg.OrgID, arg.ProjectID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveSecretDataKey = `-- name: GetActiveSecretDataKey :one

SELECT org_id, version, key_id, wrapped, active, created_at
FROM secret_data_keys
WHERE org_id = $1 AND active
`

type GetActiveSecretDataKeyRow struct {
	OrgID     string
	Version   int32
	KeyID     string
	Wrapped   []byte
	Active    bool
	CreatedAt time.Time
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) GetActiveSecretDataKey(ctx context.Context, orgID string) (GetActiveSecretDataKeyRow, error) {
	row := q.db.QueryRow(ctx, getActiveSecretDataKey, orgID)
	var i GetActiveSecretDataKeyRow
	err := row.Scan(
		&i.OrgID,
		&i.Version,
		&i.KeyID,
		&i.Wrapped,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectIDsBySlug = `-- name: GetProjectIDsBySlug :many
SELECT id, slug FROM projects
WHERE org_id = $1 AND slug = ANY ($2::text[])
`

type GetProjectIDsBySlugParams struct {
	OrgID string
	Slugs []string
}

type GetProjectIDsBySlugRow struct {
	ID   string
	Slug string
}

func (q *Queries) GetProjectIDsBySlug(ctx context.Context, arg GetProjectIDsBySlugParams) ([]GetProjectIDsBySlugRow, error) {
	rows, err := q.db.Query(ctx, getProjectIDsBySlug, arg.OrgID, arg.Slugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectIDsBySlugRow{}
	for rows.Next() {
		var i GetProjectIDsBySlugRow
		if err := rows.Scan(&i.ID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectSlugsByID = `-- name: GetProjectSlugsByID :many
SELECT id, slug FROM projects
WHERE org_id = $1 AND id = ANY ($2::text[])
`

type GetProjectSlugsByIDParams struct {
	OrgID string
	Ids   []string
}

type GetProjectSlugsByIDRow struct {
	ID   string
	Slug string
}

func (q *Queries) GetProjectSlugsByID(ctx context.Context, arg GetProjectSlugsByIDParams) ([]GetProjectSlugsByIDRow, error) {
	rows, err := q.db.Query(ctx, getProjectSlugsByID, arg.OrgID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectSlugsByIDRow{}
	for rows.Next() {
		var i GetProjectSlugsByIDRow
		if err := rows.Scan(&i.ID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSealedSecret = `-- name: GetSealedSecret :one
SELECT id, org_id, project_id, name, dek_version, value_version, ciphertext, masked, branches, allow_unprotected,
    all_projects, project_ids, created_by, updated_by, created_at, updated_at
FROM secrets
WHERE org_id = $1 AND project_id IS NOT DISTINCT FROM $2 AND name = $3
`

type GetSealedSecretParams struct {
	OrgID     string
	ProjectID *string
	Name      string
}

// GetSealedSecret returns a secret's ciphertext for decryption at lease
// time (ADR-0009 §5); never exposed through the API.
func (q *Queries) GetSealedSecret(ctx context.Context, arg GetSealedSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, getSealedSecret, arg.OrgID, arg.ProjectID, arg.Name)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.DekVersion,
		&i.ValueVersion,
		&i.Ciphertext,
		&i.Masked,
		&i.Branches,
		&i.AllowUnprotected,
		&i.AllProjects,
		&i.ProjectIds,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSecretDataKey = `-- name: GetSecretDataKey :one
SELECT org_id, version, key_id, wrapped, active, created_at
FROM secret_data_keys
WHERE org_id = $1 AND version = $2
`

type GetSecretDataKeyParams struct {
	OrgID   string
	Version int32
}

type GetSecretDataKeyRow struct {
	OrgID     string
	Version   int32
	KeyID     string
	Wrapped   []byte
	Active    bool
	CreatedAt time.Time
}

func (q *Queries) GetSecretDataKey(ctx context.Context, arg GetSecretDataKeyParams) (GetSecretDataKeyRow, error) {
	row := q.db.QueryRow(ctx, getSecretDataKey, arg.OrgID, arg.Version)
	var i GetSecretDataKeyRow
	err := row.Scan(
		&i.OrgID,
		&i.Version,
		&i.KeyID,
		&i.Wrapped,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const insertFirstSecretDataKey = `-- name: InsertFirstSecretDataKey :execrows
INSERT INTO secret_data_keys (org_id, version, key_id, wrapped, active, created_at)
VALUES ($1, 1, $2, $3, true, $4)
ON CONFLICT DO NOTHING
`

type InsertFirstSecretDataKeyParams struct {
	OrgID     string
	KeyID     string
	Wrapped   []byte
	CreatedAt time.Time
}

// InsertFirstSecretDataKey creates an org's first DEK; a concurrent
// creator loses quietly and both then read the winner's row.
func (q *Queries) InsertFirstSecretDataKey(ctx context.Context, arg InsertFirstSecretDataKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertFirstSecretDataKey,
		arg.OrgID,
		arg.KeyID,
		arg.Wrapped,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertSecret = `-- name: InsertSecret :exec
INSERT INTO secrets (id, org_id, project_id, name, dek_version, value_version, ciphertext, masked, branches,
    allow_unprotected, all_projects, project_ids, created_by, updated_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
`

type InsertSecretParams struct {
	ID               string
	OrgID            string
	ProjectID        *string
	Name             string
	DekVersion       int32
	ValueVersion     int64
	Ciphertext       []byte
	Masked           bool
	Branches         []string
	AllowUnprotected bool
	AllProjects      bool
	ProjectIds       []string
	CreatedBy        *string
	UpdatedBy        *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) InsertSecret(ctx context.Context, arg InsertSecretParams) error {
	_, err := q.db.Exec(ctx, insertSecret,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.Name,
		arg.DekVersion,
		arg.ValueVersion,
		arg.Ciphertext,
		arg.Masked,
		arg.Branches,
		arg.AllowUnprotected,
		arg.AllProjects,
		arg.ProjectIds,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listSecrets = `-- name: ListSecrets :many
SELECT id, org_id, project_id, name, dek_version, value_version, masked, branches, allow_unprotected,
    all_projects, project_ids, created_by, updated_by, created_at, updated_at
FROM secrets
WHERE org_id = $1 AND project_id IS NOT DISTINCT FROM $2
    AND ($3::text = '' OR id > $3::text)
ORDER BY id
LIMIT $4
`

type ListSecretsParams struct {
	OrgID     string
	ProjectID *string
	AfterID   string
	MaxRows   int32
}

type ListSecretsRow struct {
	ID               string
	OrgID            string
	ProjectID        *string
	Name             string
	DekVersion       int32
	ValueVersion     int64
	Masked           bool
	Branches         []string
	AllowUnprotected bool
	AllProjects      bool
	ProjectIds       []string
	CreatedBy        *string
	UpdatedBy        *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) ListSecrets(ctx context.Context, arg ListSecretsParams) ([]ListSecretsRow, error) {
	rows, err := q.db.Query(ctx, listSecrets,
		arg.OrgID,
		arg.ProjectID,
		arg.AfterID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretsRow{}
	for rows.Next() {
		var i ListSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Name,
			&i.DekVersion,
			&i.ValueVersion,
			&i.Masked,
			&i.Branches,
			&i.AllowUnprotected,
			&i.AllProjects,
			&i.ProjectIds,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSecret = `-- name: LockSecret :one
SELECT id, org_id, project_id, name, dek_version, value_version, masked, branches, allow_unprotected,
    all_projects, project_ids, created_by, updated_by, created_at, updated_at
FROM secrets
WHERE org_id = $1 AND project_id IS NOT DISTINCT FROM $2 AND name = $3
FOR UPDATE
`

type LockSecretParams struct {
	OrgID     string
	ProjectID *string
	Name      string
}

type LockSecretRow struct {
	ID               string
	OrgID            string
	ProjectID        *string
	Name             string
	DekVersion       int32
	ValueVersion     int64
	Masked           bool
	Branches         []string
	AllowUnprotected bool
	AllProjects      bool
	ProjectIds       []string
	CreatedBy        *string
	UpdatedBy        *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) LockSecret(ctx context.Context, arg LockSecretParams) (LockSecretRow, error) {
	row := q.db.QueryRow(ctx, lockSecret, arg.OrgID, arg.ProjectID, arg.Name)
	var i LockSecretRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.DekVersion,
		&i.ValueVersion,
		&i.Masked,
		&i.Branches,
		&i.AllowUnprotected,
		&i.AllProjects,
		&i.ProjectIds,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockSecretScope = `-- name: LockSecretScope :exec
SELECT pg_advisory_xact_lock(hashtextextended('kiln.secrets:' || $1::text, 0))
`

// LockSecretScope serializes secret creation in one scope for the current
// transaction, so the per-scope limit cannot be raced.
func (q *Queries) LockSecretScope(ctx context.Context, scopeKey string) error {
	_, err := q.db.Exec(ctx, lockSecretScope, scopeKey)
	return err
}

const updateSecret = `-- name: UpdateSecret :execrows
UPDATE secrets
SET dek_version = $1, value_version = $2, ciphertext = $3,
    masked = $4, branches = $5, allow_unprotected = $6,
    all_projects = $7, project_ids = $8, updated_by = $9,
    updated_at = $10
WHERE org_id = $11 AND id = $12 AND value_version = $2 - 1
`

type UpdateSecretParams struct {
	DekVersion       int32
	ValueVersion     int64
	Ciphertext       []byte
	Masked           bool
	Branches         []string
	AllowUnprotected bool
	AllProjects      bool
	ProjectIds       []string
	UpdatedBy        *string
	UpdatedAt        time.Time
	OrgID            string
	ID               string
}

func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSecret,
		arg.DekVersion,
		arg.ValueVersion,
		arg.Ciphertext,
		arg.Masked,
		arg.Branches,
		arg.AllowUnprotected,
		arg.AllProjects,
		arg.ProjectIds,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.OrgID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
