// SPDX-License-Identifier: Apache-2.0

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"
)

const createAccessToken = `-- name: CreateAccessToken :exec
INSERT INTO desktop_access_tokens (token_hash, grant_id, created_at, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateAccessTokenParams struct {
	TokenHash []byte
	GrantID   string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) error {
	_, err := q.db.Exec(ctx, createAccessToken,
		arg.TokenHash,
		arg.GrantID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createDesktopAuthCode = `-- name: CreateDesktopAuthCode :exec
INSERT INTO desktop_auth_codes (code_hash, user_id, code_challenge, redirect_uri, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateDesktopAuthCodeParams struct {
	CodeHash      []byte
	UserID        string
	CodeChallenge string
	RedirectUri   string
	CreatedAt     time.Time
	ExpiresAt     time.Time
}

func (q *Queries) CreateDesktopAuthCode(ctx context.Context, arg CreateDesktopAuthCodeParams) error {
	_, err := q.db.Exec(ctx, createDesktopAuthCode,
		arg.CodeHash,
		arg.UserID,
		arg.CodeChallenge,
		arg.RedirectUri,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createDesktopGrant = `-- name: CreateDesktopGrant :exec
INSERT INTO desktop_grants (id, user_id, created_at, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateDesktopGrantParams struct {
	ID        string
	UserID    string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateDesktopGrant(ctx context.Context, arg CreateDesktopGrantParams) error {
	_, err := q.db.Exec(ctx, createDesktopGrant,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createLoginState = `-- name: CreateLoginState :exec
INSERT INTO login_states (state_hash, client, nonce, idp_code_verifier, return_to,
    desktop_redirect_uri, desktop_code_challenge, desktop_state, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateLoginStateParams struct {
	StateHash            []byte
	Client               string
	Nonce                string
	IdpCodeVerifier      string
	ReturnTo             string
	DesktopRedirectUri   string
	DesktopCodeChallenge string
	DesktopState         string
	CreatedAt            time.Time
	ExpiresAt            time.Time
}

func (q *Queries) CreateLoginState(ctx context.Context, arg CreateLoginStateParams) error {
	_, err := q.db.Exec(ctx, createLoginState,
		arg.StateHash,
		arg.Client,
		arg.Nonce,
		arg.IdpCodeVerifier,
		arg.ReturnTo,
		arg.DesktopRedirectUri,
		arg.DesktopCodeChallenge,
		arg.DesktopState,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO desktop_refresh_tokens (token_hash, grant_id, created_at, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateRefreshTokenParams struct {
	TokenHash []byte
	GrantID   string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.TokenHash,
		arg.GrantID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createWebSession = `-- name: CreateWebSession :exec

INSERT INTO web_sessions (id, token_hash, user_id, created_at, last_seen_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateWebSessionParams struct {
	ID         string
	TokenHash  []byte
	UserID     string
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) CreateWebSession(ctx context.Context, arg CreateWebSessionParams) error {
	_, err := q.db.Exec(ctx, createWebSession,
		arg.ID,
		arg.TokenHash,
		arg.UserID,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredAccessTokens = `-- name: DeleteExpiredAccessTokens :execrows
DELETE FROM desktop_access_tokens WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredAccessTokens(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAccessTokens, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredDesktopAuthCodes = `-- name: DeleteExpiredDesktopAuthCodes :execrows
DELETE FROM desktop_auth_codes WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredDesktopAuthCodes(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredDesktopAuthCodes, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredDesktopGrants = `-- name: DeleteExpiredDesktopGrants :execrows
DELETE FROM desktop_grants WHERE expires_at < $1
`

// Grants cascade to their remaining tokens.
func (q *Queries) DeleteExpiredDesktopGrants(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredDesktopGrants, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredLoginStates = `-- name: DeleteExpiredLoginStates :execrows
DELETE FROM login_states WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredLoginStates(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredLoginStates, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM desktop_refresh_tokens WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredWebSessions = `-- name: DeleteExpiredWebSessions :execrows
DELETE FROM web_sessions WHERE expires_at < $1
`

// Sessions and codes are kept for a day after expiry for incident review.
func (q *Queries) DeleteExpiredWebSessions(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredWebSessions, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccessToken = `-- name: GetAccessToken :one
SELECT t.token_hash, t.grant_id, t.expires_at, g.user_id,
    g.revoked_at AS grant_revoked_at, g.expires_at AS grant_expires_at
FROM desktop_access_tokens t
JOIN desktop_grants g ON g.id = t.grant_id
WHERE t.token_hash = $1
`

type GetAccessTokenRow struct {
	TokenHash      []byte
	GrantID        string
	ExpiresAt      time.Time
	UserID         string
	GrantRevokedAt *time.Time
	GrantExpiresAt time.Time
}

func (q *Queries) GetAccessToken(ctx context.Context, tokenHash []byte) (GetAccessTokenRow, error) {
	row := q.db.QueryRow(ctx, getAccessToken, tokenHash)
	var i GetAccessTokenRow
	err := row.Scan(
		&i.TokenHash,
		&i.GrantID,
		&i.ExpiresAt,
		&i.UserID,
		&i.GrantRevokedAt,
		&i.GrantExpiresAt,
	)
	return i, err
}

const getDesktopGrant = `-- name: GetDesktopGrant :one
SELECT id, user_id, created_at, expires_at, revoked_at
FROM desktop_grants WHERE id = $1
`

func (q *Queries) GetDesktopGrant(ctx context.Context, id string) (DesktopGrant, error) {
	row := q.db.QueryRow(ctx, getDesktopGrant, id)
	var i DesktopGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT token_hash, grant_id, created_at, expires_at, used_at
FROM desktop_refresh_tokens WHERE token_hash = $1
FOR UPDATE
`

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, tokenHash []byte) (DesktopRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, tokenHash)
	var i DesktopRefreshToken
	err := row.Scan(
		&i.TokenHash,
		&i.GrantID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getWebSessionByHash = `-- name: GetWebSessionByHash :one
SELECT id, token_hash, user_id, created_at, last_seen_at, expires_at, revoked_at
FROM web_sessions
WHERE token_hash = $1
`

func (q *Queries) GetWebSessionByHash(ctx context.Context, tokenHash []byte) (WebSession, error) {
	row := q.db.QueryRow(ctx, getWebSessionByHash, tokenHash)
	var i WebSession
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :exec
UPDATE desktop_refresh_tokens SET used_at = $2 WHERE token_hash = $1
`

type MarkRefreshTokenUsedParams struct {
	TokenHash []byte
	UsedAt    *time.Time
}

func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) error {
	_, err := q.db.Exec(ctx, markRefreshTokenUsed, arg.TokenHash, arg.UsedAt)
	return err
}

const revokeDesktopGrant = `-- name: RevokeDesktopGrant :exec
UPDATE desktop_grants SET revoked_at = $2
WHERE id = $1 AND revoked_at IS NULL
`

type RevokeDesktopGrantParams struct {
	ID        string
	RevokedAt *time.Time
}

func (q *Queries) RevokeDesktopGrant(ctx context.Context, arg RevokeDesktopGrantParams) error {
	_, err := q.db.Exec(ctx, revokeDesktopGrant, arg.ID, arg.RevokedAt)
	return err
}

const revokeWebSession = `-- name: RevokeWebSession :exec
UPDATE web_sessions SET revoked_at = $2
WHERE id = $1 AND revoked_at IS NULL
`

type RevokeWebSessionParams struct {
	ID        string
	RevokedAt *time.Time
}

func (q *Queries) RevokeWebSession(ctx context.Context, arg RevokeWebSessionParams) error {
	_, err := q.db.Exec(ctx, revokeWebSession, arg.ID, arg.RevokedAt)
	return err
}

const takeLoginState = `-- name: TakeLoginState :one
DELETE FROM login_states
WHERE state_hash = $1
RETURNING state_hash, client, nonce, idp_code_verifier, return_to,
    desktop_redirect_uri, desktop_code_challenge, desktop_state, created_at, expires_at
`

// TakeLoginState deletes and returns the state so it can be used only once.
func (q *Queries) TakeLoginState(ctx context.Context, stateHash []byte) (LoginState, error) {
	row := q.db.QueryRow(ctx, takeLoginState, stateHash)
	var i LoginState
	err := row.Scan(
		&i.StateHash,
		&i.Client,
		&i.Nonce,
		&i.IdpCodeVerifier,
		&i.ReturnTo,
		&i.DesktopRedirectUri,
		&i.DesktopCodeChallenge,
		&i.DesktopState,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const touchWebSession = `-- name: TouchWebSession :exec
UPDATE web_sessions SET last_seen_at = $2
WHERE id = $1 AND revoked_at IS NULL
`

type TouchWebSessionParams struct {
	ID         string
	LastSeenAt time.Time
}

func (q *Queries) TouchWebSession(ctx context.Context, arg TouchWebSessionParams) error {
	_, err := q.db.Exec(ctx, touchWebSession, arg.ID, arg.LastSeenAt)
	return err
}

const useDesktopAuthCode = `-- name: UseDesktopAuthCode :one
UPDATE desktop_auth_codes SET used_at = $1
WHERE code_hash = $2 AND used_at IS NULL
RETURNING code_hash, user_id, code_challenge, redirect_uri, created_at, expires_at, used_at
`

type UseDesktopAuthCodeParams struct {
	Now      *time.Time
	CodeHash []byte
}

// UseDesktopAuthCode marks an unused code as used and returns it; a second
// redemption finds no row.
func (q *Queries) UseDesktopAuthCode(ctx context.Context, arg UseDesktopAuthCodeParams) (DesktopAuthCode, error) {
	row := q.db.QueryRow(ctx, useDesktopAuthCode, arg.Now, arg.CodeHash)
	var i DesktopAuthCode
	err := row.Scan(
		&i.CodeHash,
		&i.UserID,
		&i.CodeChallenge,
		&i.RedirectUri,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}
