// SPDX-License-Identifier: Apache-2.0

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package db

import (
	"context"
	"time"
)

const countActiveAPITokens = `-- name: CountActiveAPITokens :one
SELECT count(*) FROM api_tokens
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > $2
`

type CountActiveAPITokensParams struct {
	UserID    string
	ExpiresAt time.Time
}

func (q *Queries) CountActiveAPITokens(ctx context.Context, arg CountActiveAPITokensParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAPITokens, arg.UserID, arg.ExpiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIToken = `-- name: CreateAPIToken :one

INSERT INTO api_tokens (id, user_id, name, prefix, token_hash, scopes, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, name, prefix, scopes, created_at, expires_at, last_used_at, revoked_at
`

type CreateAPITokenParams struct {
	ID        string
	UserID    string
	Name      string
	Prefix    string
	TokenHash []byte
	Scopes    []string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type CreateAPITokenRow struct {
	ID         string
	UserID     string
	Name       string
	Prefix     string
	Scopes     []string
	CreatedAt  time.Time
	ExpiresAt  time.Time
	LastUsedAt *time.Time
	RevokedAt  *time.Time
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (CreateAPITokenRow, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.TokenHash,
		arg.Scopes,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i CreateAPITokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.Scopes,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, user_id, name, prefix, scopes, created_at, expires_at, last_used_at, revoked_at
FROM api_tokens WHERE token_hash = $1
`

type GetAPITokenByHashRow struct {
	ID         string
	UserID     string
	Name       string
	Prefix     string
	Scopes     []string
	CreatedAt  time.Time
	ExpiresAt  time.Time
	LastUsedAt *time.Time
	RevokedAt  *time.Time
}

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash []byte) (GetAPITokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i GetAPITokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.Scopes,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, user_id, name, prefix, scopes, created_at, expires_at, last_used_at, revoked_at
FROM api_tokens
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY id
`

type ListAPITokensRow struct {
	ID         string
	UserID     string
	Name       string
	Prefix     string
	Scopes     []string
	CreatedAt  time.Time
	ExpiresAt  time.Time
	LastUsedAt *time.Time
	RevokedAt  *time.Time
}

func (q *Queries) ListAPITokens(ctx context.Context, userID string) ([]ListAPITokensRow, error) {
	rows, err := q.db.Query(ctx, listAPITokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPITokensRow{}
	for rows.Next() {
		var i ListAPITokensRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.Scopes,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :execrows
UPDATE api_tokens SET revoked_at = $1
WHERE id = $2 AND user_id = $3 AND revoked_at IS NULL
`

type RevokeAPITokenParams struct {
	Now    *time.Time
	ID     string
	UserID string
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIToken, arg.Now, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = $1
WHERE id = $2
  AND (last_used_at IS NULL OR last_used_at < $1 - interval '1 minute')
`

type TouchAPITokenParams struct {
	Now *time.Time
	ID  string
}

// Coalesces last-used writes to at most one per minute per token.
func (q *Queries) TouchAPIToken(ctx context.Context, arg TouchAPITokenParams) error {
	_, err := q.db.Exec(ctx, touchAPIToken, arg.Now, arg.ID)
	return err
}
