// SPDX-License-Identifier: Apache-2.0

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"
)

const claimPendingUser = `-- name: ClaimPendingUser :one
UPDATE users
SET oidc_issuer = $1, oidc_subject = $2,
    display_name = $3,
    instance_admin = instance_admin OR $4::boolean
WHERE lower(email) = lower($5) AND oidc_issuer IS NULL
RETURNING id, oidc_issuer, oidc_subject, email, display_name, instance_admin, created_at
`

type ClaimPendingUserParams struct {
	Issuer             *string
	Subject            *string
	DisplayName        string
	GrantInstanceAdmin bool
	Email              string
}

// ClaimPendingUser binds an IdP identity to an invited (unclaimed) account.
func (q *Queries) ClaimPendingUser(ctx context.Context, arg ClaimPendingUserParams) (User, error) {
	row := q.db.QueryRow(ctx, claimPendingUser,
		arg.Issuer,
		arg.Subject,
		arg.DisplayName,
		arg.GrantInstanceAdmin,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Email,
		&i.DisplayName,
		&i.InstanceAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const createPendingUser = `-- name: CreatePendingUser :one
INSERT INTO users (id, email, display_name, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, oidc_issuer, oidc_subject, email, display_name, instance_admin, created_at
`

type CreatePendingUserParams struct {
	ID          string
	Email       string
	DisplayName string
	CreatedAt   time.Time
}

func (q *Queries) CreatePendingUser(ctx context.Context, arg CreatePendingUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createPendingUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Email,
		&i.DisplayName,
		&i.InstanceAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, oidc_issuer, oidc_subject, email, display_name, instance_admin, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, oidc_issuer, oidc_subject, email, display_name, instance_admin, created_at
`

type CreateUserParams struct {
	ID            string
	OidcIssuer    *string
	OidcSubject   *string
	Email         string
	DisplayName   string
	InstanceAdmin bool
	CreatedAt     time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.OidcIssuer,
		arg.OidcSubject,
		arg.Email,
		arg.DisplayName,
		arg.InstanceAdmin,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Email,
		&i.DisplayName,
		&i.InstanceAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, oidc_issuer, oidc_subject, email, display_name, instance_admin, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Email,
		&i.DisplayName,
		&i.InstanceAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, oidc_issuer, oidc_subject, email, display_name, instance_admin, created_at
FROM users
WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Email,
		&i.DisplayName,
		&i.InstanceAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByOIDC = `-- name: GetUserByOIDC :one

SELECT id, oidc_issuer, oidc_subject, email, display_name, instance_admin, created_at
FROM users
WHERE oidc_issuer = $1 AND oidc_subject = $2
`

type GetUserByOIDCParams struct {
	OidcIssuer  *string
	OidcSubject *string
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) GetUserByOIDC(ctx context.Context, arg GetUserByOIDCParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOIDC, arg.OidcIssuer, arg.OidcSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Email,
		&i.DisplayName,
		&i.InstanceAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET email = $1,
    display_name = $2,
    instance_admin = instance_admin OR $3::boolean
WHERE id = $4
RETURNING id, oidc_issuer, oidc_subject, email, display_name, instance_admin, created_at
`

type UpdateUserProfileParams struct {
	Email              string
	DisplayName        string
	GrantInstanceAdmin bool
	ID                 string
}

// Instance admin can be granted (bootstrap list) but never revoked by sign-in.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.Email,
		arg.DisplayName,
		arg.GrantInstanceAdmin,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Email,
		&i.DisplayName,
		&i.InstanceAdmin,
		&i.CreatedAt,
	)
	return i, err
}
