// SPDX-License-Identifier: Apache-2.0
import {
  convertCssVariables,
  DEFAULT_THEME,
  defaultCssVariablesResolver,
  mergeMantineTheme,
} from "@mantine/core";

import { kilnTheme } from "./theme.ts";

const HEADER = `/* SPDX-License-Identifier: Apache-2.0 */
/* GENERATED by packages/ui/scripts/build-theme-css.ts from src/theme.ts. Do not edit. */
`;

/** Renders the theme's CSS variables exactly as MantineProvider would inject them. */
export function renderThemeCss(): string {
  const theme = mergeMantineTheme(DEFAULT_THEME, kilnTheme);
  // Same selector MantineProvider uses by default (`:root` and `:host`).
  return HEADER + convertCssVariables(defaultCssVariablesResolver(theme), ":root, :host") + "\n";
}
